# ---------------------
# Docker Compose file for Ansible target server
# This file sets up a personal server with Ansible
# ---------------------

version: "3.8"
services:
  personal-server:
    container_name: ansible-target-server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "2222:22"
      - "8080:80"
    # Dev note: crucial fix: Grant the container permission
    # to administer the network stack.
    cap_add:
      - NET_ADMIN
