---
galaxy_info:
  role_name: webserver
  author: YogeshT22
  description: Install and configure a hardened Nginx web server
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags: [nginx, webserver, security, linux]
dependencies: []
