---
galaxy_info:
  role_name: hardening
  author: YogeshT22
  description: OS-level hardening - sysctl, auditd, MOTD, file permissions
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags: [hardening, security, sysctl, linux]
dependencies: []
