---
# webserver/defaults/main.yml
webserver_server_name: "_"
webserver_admin_email: "admin@example.com"
webserver_worker_connections: 1024
webserver_ufw_allowed_ports:
  - "22"
  - "80"
  - "443"
webserver_security_update_hour: "2"
webserver_security_update_minute: "0"
